language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g bower grunt-cli protractor
install:
  - npm install
script:
  - grunt test:development
  - grunt test
  # - grunt e2e --ci
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
sudo: false
